apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-1
  labels:
    app: demo-rc
    type: rc-test
spec:
  template:
    metadata:
      name: rc-container
      labels:
        app: demo-nginx
        type: rc-nginx
    spec:
      containers:
        - name: rc-nginx
          image: nginx
  replicas: 3